Repository PHPCSStandards/PHPCSUtils, pull requests merged in 2023-08, with the labels that each got.

#500 Update for PHPUnit Polyfills 1.1.0
  Tests/PolyfilledTestCase.php
  composer.json
Labels: Type: chores/QA

#502 Tests: minor clean up
  Tests/Internal/IsShortArrayOrList/SolveTest.php
  Tests/Internal/IsShortArrayOrList/WalkInsideTest.php
  Tests/Internal/IsShortArrayOrList/WalkOutsideTest.php
  Tests/Utils/Namespaces/DetermineNamespaceTest.php
Labels: Type: chores/QA

#503 [NoFile]Cache/SetTest: pass correct type to base_convert()
  Tests/Internal/Cache/SetTest.php
  Tests/Internal/NoFileCache/SetTest.php
Labels: Type: chores/QA

#505 CS/QA: remove some redundant code
  Tests/BackCompat/Helper/GetVersionTest.php
Labels: Type: chores/QA

#504 Exceptions/TestTargetNotFound: improve defensive coding
  PHPCSUtils/Exceptions/TestTargetNotFound.php
Labels: Type: chores/QA

#506 Docs: various `@var`/`@param`/`@return` tag improvements
  PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php
  PHPCSUtils/BackCompat/BCFile.php
  PHPCSUtils/BackCompat/BCTokens.php
  PHPCSUtils/BackCompat/Helper.php
  PHPCSUtils/Exceptions/TestTargetNotFound.php
  PHPCSUtils/Internal/Cache.php
  PHPCSUtils/Internal/IsShortArrayOrList.php
  PHPCSUtils/Internal/IsShortArrayOrListWithCache.php
  PHPCSUtils/Internal/NoFileCache.php
  PHPCSUtils/Internal/StableCollections.php
  PHPCSUtils/TestUtils/UtilityMethodTestCase.php
  PHPCSUtils/Tokens/Collections.php
  PHPCSUtils/Utils/Arrays.php
  PHPCSUtils/Utils/Conditions.php
  PHPCSUtils/Utils/ControlStructures.php
  PHPCSUtils/Utils/FunctionDeclarations.php
  PHPCSUtils/Utils/Lists.php
  PHPCSUtils/Utils/MessageHelper.php
  PHPCSUtils/Utils/Numbers.php
  PHPCSUtils/Utils/ObjectDeclarations.php
  PHPCSUtils/Utils/Operators.php
  PHPCSUtils/Utils/Parentheses.php
  PHPCSUtils/Utils/PassedParameters.php
  PHPCSUtils/Utils/Scopes.php
  PHPCSUtils/Utils/UseStatements.php
  PHPCSUtils/Utils/Variables.php
  Tests/AbstractSniffs/AbstractArrayDeclaration/AbstractArrayDeclarationSniffTest.php
  Tests/AbstractSniffs/AbstractArrayDeclaration/ArrayDeclarationSniffTestDouble.php
  Tests/BackCompat/BCFile/GetConditionTest.php
  Tests/BackCompat/BCFile/GetMemberPropertiesTest.php
  Tests/BackCompat/BCTokens/UnchangedTokenArraysTest.php
  Tests/Fixers/SpacesFixer/SpacesFixerAtEOFTest.php
  Tests/Fixers/SpacesFixer/SpacesFixerNewlineTest.php
  Tests/Fixers/SpacesFixer/SpacesFixerNoSpaceTest.php
  Tests/Fixers/SpacesFixer/SpacesFixerOneSpaceTest.php
  Tests/Fixers/SpacesFixer/SpacesFixerTestCase.php
  Tests/Fixers/SpacesFixer/SpacesFixerTwoSpaceTest.php
  Tests/Fixers/SpacesFixer/TrailingCommentHandlingNewlineTest.php
  Tests/Fixers/SpacesFixer/TrailingCommentHandlingTest.php
  Tests/Utils/Arrays/GetDoubleArrowPtrTest.php
  Tests/Utils/FunctionDeclarations/GetParametersDiffTest.php
  Tests/Utils/MessageHelper/AddMessageTest.php
  Tests/Utils/Numbers/NumberTypesTest.php
  Tests/Utils/Parentheses/ParenthesesTest.php
  Tests/Utils/PassedParameters/GetParameterFromStackTest.php
  Tests/Utils/PassedParameters/GetParametersWithLimitTest.php
  Tests/Utils/TextStrings/GetCompleteTextStringTest.php
  Tests/Utils/TextStrings/InterpolatedVariablesTest.php
  Tests/Utils/Variables/GetMemberPropertiesDiffTest.php
  Tests/Xtra/Messages/HasNewLineSupportTest.php
  phpcs.xml.dist
Labels: Type: documentation

#507 GH Actions: update doc generation workflow
  .github/workflows/update-docs.yml
Labels: Type: documentation, Type: chores/QA

#501 GHPages/UpdateWebsite: minor fix
  .github/GHPages/UpdateWebsite.php
Labels: Type: chores/QA

#508 Add PHPStan to QA checks
  .gitattributes
  .github/workflows/basics.yml
  .gitignore
  phpstan.neon.dist
Labels: Type: chores/QA

#509 Correct error message when path not found
  .github/GHPages/UpdateWebsite.php
Labels: Type: chores/QA
