Repository PHPCSStandards/PHPCSUtils, pull requests merged in 2023-01, with the labels that each got.

#417 README: minor improvement to installation instructions
  README.md
Labels: Type: documentation

#418 GH Pages: minor tweaks
  docs/_config.yml
  docs/_layouts/default.html
  docs/assets/css/style.scss
Labels: Type: documentation

#420 Changelog for PHPCSUtils 1.0.0
  CHANGELOG.md
Labels: Type: documentation, Type: meta

#422 Fix namespace of IsPHPReservedVarNameTest
  Tests/Utils/Variables/IsPHPReservedVarNameTest.php
Labels: Type: chores/QA

#425 Docs: QA on `@since` tags
  PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php
  PHPCSUtils/BackCompat/BCFile.php
  PHPCSUtils/BackCompat/BCTokens.php
  PHPCSUtils/BackCompat/Helper.php
  PHPCSUtils/Exceptions/InvalidTokenArray.php
  PHPCSUtils/Exceptions/TestFileNotFound.php
  PHPCSUtils/Exceptions/TestMarkerNotFound.php
  PHPCSUtils/Exceptions/TestTargetNotFound.php
  PHPCSUtils/Internal/Cache.php
  PHPCSUtils/Internal/IsShortArrayOrList.php
  PHPCSUtils/Internal/IsShortArrayOrListWithCache.php
  PHPCSUtils/Internal/NoFileCache.php
  PHPCSUtils/TestUtils/UtilityMethodTestCase.php
  PHPCSUtils/Tokens/Collections.php
  PHPCSUtils/Tokens/TokenHelper.php
  PHPCSUtils/Utils/Arrays.php
  PHPCSUtils/Utils/Conditions.php
  PHPCSUtils/Utils/Context.php
  PHPCSUtils/Utils/ControlStructures.php
  PHPCSUtils/Utils/FunctionDeclarations.php
  PHPCSUtils/Utils/Lists.php
  PHPCSUtils/Utils/MessageHelper.php
  PHPCSUtils/Utils/Namespaces.php
  PHPCSUtils/Utils/NamingConventions.php
  PHPCSUtils/Utils/Numbers.php
  PHPCSUtils/Utils/ObjectDeclarations.php
  PHPCSUtils/Utils/Operators.php
  PHPCSUtils/Utils/Parentheses.php
  PHPCSUtils/Utils/PassedParameters.php
  PHPCSUtils/Utils/Scopes.php
  PHPCSUtils/Utils/TextStrings.php
  PHPCSUtils/Utils/UseStatements.php
  PHPCSUtils/Utils/Variables.php
Labels: Type: documentation

#427 Composer: minor (dev) autoloading tweak
  composer.json
Labels: Type: chores/QA

#428 Composer: allow for the 1.0.0 version of the Composer PHPCS plugin
  composer.json
Labels: Type: enhancement

#429 Changelog for PHPCSUtils 1.0.1
  CHANGELOG.md
Labels: Type: documentation, Type: meta

#430 Release 1.0.1
  CHANGELOG.md
  PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php
  PHPCSUtils/BackCompat/BCFile.php
  PHPCSUtils/BackCompat/BCTokens.php
  PHPCSUtils/BackCompat/Helper.php
  PHPCSUtils/Exceptions/InvalidTokenArray.php
  PHPCSUtils/Exceptions/TestFileNotFound.php
  PHPCSUtils/Exceptions/TestMarkerNotFound.php
  PHPCSUtils/Exceptions/TestTargetNotFound.php
  PHPCSUtils/Internal/Cache.php
  PHPCSUtils/Internal/IsShortArrayOrList.php
  PHPCSUtils/Internal/IsShortArrayOrListWithCache.php
  PHPCSUtils/Internal/NoFileCache.php
  PHPCSUtils/TestUtils/UtilityMethodTestCase.php
  PHPCSUtils/Tokens/Collections.php
  PHPCSUtils/Tokens/TokenHelper.php
  PHPCSUtils/Utils/Arrays.php
  PHPCSUtils/Utils/Conditions.php
  PHPCSUtils/Utils/Context.php
  PHPCSUtils/Utils/ControlStructures.php
  PHPCSUtils/Utils/FunctionDeclarations.php
  PHPCSUtils/Utils/Lists.php
  PHPCSUtils/Utils/MessageHelper.php
  PHPCSUtils/Utils/Namespaces.php
  PHPCSUtils/Utils/NamingConventions.php
  PHPCSUtils/Utils/Numbers.php
  PHPCSUtils/Utils/ObjectDeclarations.php
  PHPCSUtils/Utils/Operators.php
  PHPCSUtils/Utils/Parentheses.php
  PHPCSUtils/Utils/PassedParameters.php
  PHPCSUtils/Utils/Scopes.php
  PHPCSUtils/Utils/TextStrings.php
  PHPCSUtils/Utils/UseStatements.php
  PHPCSUtils/Utils/Variables.php
  Tests/Utils/Variables/IsPHPReservedVarNameTest.php
  composer.json
Labels: Type: meta
