Repository PHPCSStandards/PHPCSUtils, pull requests merged in 2023-11, with the labels that each got.

#518 Fix markdownlint CI job failure
  .markdownlint-cli2.yaml
  README.md
Labels: Type: chores/QA

#519 Defer to organisation security policy
  .github/SECURITY.md
Labels: Type: documentation, Type: chores/QA

#520 GH Actions: various tweaks
  .github/workflows/basics.yml
  .yamllint.yml
  phpstan.neon.dist
Labels: Type: chores/QA

#521 Composer.json: add link to security policy
  composer.json
Labels: Type: documentation

#522 GH Actions: update for the release of PHP 8.3
  .github/workflows/test.yml
  README.md
Labels: Type: chores/QA

#514 Update "tested on" badge in README to include PHP v8.3
  README.md
Labels: Type: documentation
