Repository PHPCSStandards/PHPCSUtils, pull requests merged in 2025-03, with the labels that each got.

#646 BCFile::getMemberProperties(): sync with upstream
  PHPCSUtils/BackCompat/BCFile.php
  PHPCSUtils/Tokens/Collections.php
  PHPCSUtils/Utils/Variables.php
  Tests/BackCompat/BCFile/GetMemberPropertiesTest.inc
  Tests/BackCompat/BCFile/GetMemberPropertiesTest.php
Labels: Type: enhancement, Feature: backcompat layer, Feature: (sniff) utils, Type: sync with upstream

#647 GH Actions: use the xmllint-validate action runner
  .github/workflows/basics.yml
Labels: Type: chores/QA

#649 BCFile/FunctionDeclarations::get[Method]Parameters(): add extra test
  Tests/BackCompat/BCFile/GetMethodParametersTest.inc
  Tests/BackCompat/BCFile/GetMethodParametersTest.php
Labels: Type: chores/QA, Feature: (sniff) utils, Type: sync with upstream
